# This file is automatically generated from Hubbard setup.py
# Git information (specific commit, etc.)
git_revision = 'cafcf9febbf16e647c308ce40a6b753f000a951c'
git_revision_short = git_revision[:7]
git_count = 1

# Version information
major   = 0
minor   = 0
micro   = 1

# Release tag
release = 'v'+'.'.join(map(str,[major, minor, micro]))

# Version (release + count)
version = release
if git_count > 0:
    # Add git-revision to the version string
    version += '+' + str(git_count)

# Extensive version description
label   = '0.0.1'
